dist: trusty
language: php

php:
  - 5.6

env:
  global:
     - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
     - DRUPAL_VERSION='7.x'
     - DRUSH_VERSION='7.*'
     - PHPCS_VERSION='1.5.*@dev'
     - CODER_VERSION='dev-7.x-2.x'

before_script:
  # Ensure we have the latest sources.
  - sudo apt-get -y update

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Drush.
  - composer require drush/drush:$DRUSH_VERSION

  # Codesniffer.
  - composer require squizlabs/php_codesniffer:$PHPCS_VERSION

  # Coder.
  - composer require drupal/coder:$CODER_VERSION
  - ln -s $TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer/Drupal $TRAVIS_BUILD_DIR/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/

  # Ensure the PHP environment is ready.
  - phpenv rehash

script:
  # - test -d $TRAVIS_BUILD_DIR/src/modules && bin/phpmd $TRAVIS_BUILD_DIR/src/modules text phpmd.xml
  # - test -d $TRAVIS_BUILD_DIR/src/all/modules/custom && bin/phpmd $TRAVIS_BUILD_DIR/src/themes text phpmd.xml
  - test -d $TRAVIS_BUILD_DIR/src/modules && bin/phpcs --extensions=info,module,install,inc,php --ignore=*.pages_default.inc,*.views_default.inc,*.features.*,*.strongarm.* --report=full --standard=Drupal $TRAVIS_BUILD_DIR/src/modules
  - test -d $TRAVIS_BUILD_DIR/src/themes && bin/phpcs --extensions=info,module,install,inc,php --report=full --standard=Drupal $TRAVIS_BUILD_DIR/src/themes
