language: php

php:
  - 5.6

env:
  global:
     - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
     - DRUPAL_VERSION='7.x'
     - DRUSH_VERSION='7.*'
     - PHPCS_VERSION='1.5.*@dev'
     - CODER_VERSION='dev-7.x-2.x'

before_script:
  # Ensure we have the latest sources.
  - sudo apt-get -y update

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Composering!
  - composer install

  # Ensure the PHP environment is ready.
  - phpenv rehash

script:
  - bin/phpcs --standard=phpcs.xml --report=full
  - bin/phpmd src/modules text phpmd.xml
