<?php
/**
 * @file
 * oa_apachesolr.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function oa_apachesolr_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "apachesolr" && $api == "apachesolr_environments") {
    return array("version" => "1");
  }
  if ($module == "facetapi" && $api == "facetapi_defaults") {
    return array("version" => "1");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}
