<?php
/**
 * @file
 * Code for the Action Points feature.
 */

include_once 'iasc_action_points.features.inc';

/**
 * Implements hook_field_access().
 *
 * Makes sure AP focal points can only edit the status and
 * progress overview fields.
 */
function iasc_action_points_field_access($op, $field, $entity_type, $entity, $account) {
  $fields = array(
    'title_field',
    'field_ap_date',
    'field_ap_topic',
    'body',
    'field_ap_responsibility',
    'field_date',
    'field_contact',
  );

  if ($op == 'edit'
    && $entity_type == 'node'
    && isset($entity)
    && $entity->type == 'action_point'
    && in_array($field['field_name'], $fields)
  ) {
    $admin = user_role_load_by_name('administrator');
    if (!user_has_role($admin->rid, $account)) {
      return FALSE;
    }
  }
  return TRUE;
}

/**
 * Implements template_preprocess_views_view().
 */
function iasc_action_points_preprocess_views_view(&$vars) {
  if ($vars['view']->name == 'iasc_action_points') {
    drupal_add_js(drupal_get_path('module', 'iasc_action_points') . '/lib/jspdf.debug.js');
    drupal_add_js(drupal_get_path('module', 'iasc_action_points') . '/lib/jspdf.plugin.autotable.js');
    drupal_add_js(drupal_get_path('module', 'iasc_action_points') . '/iasc_action_points.js');
  }
}
