<?php
/**
 * @file
 * Code for the iasc meeting feature.
 */

include_once 'iasc_meeting.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function iasc_meeting_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function iasc_meeting_field_formatter_info_alter(&$info) {
  // Use our version of field_formatter_view.
  $info['oa_events_date_formatter']['module'] = 'iasc_meeting';
}

/**
 * Implements hook_field_formatter_view().
 */
function iasc_meeting_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  // We need to add the year to the date formatter.
  // This doesn't seem to be easily alterable.
  if ($display['type'] == 'oa_events_date_formatter') {
    $event_info = oa_events_find_next_event($items);
    $item = $event_info['event'];
    // Create Date objects from item values.
    $start_date = new DateObject($item['value'], $item['timezone'], DATE_FORMAT_UNIX);
    $end_date = new DateObject($item['value2'], $item['timezone'], DATE_FORMAT_UNIX);

    // Create an array of month / day information for ease of use.
    $dates = array(
      'start' => array(
        'day' => date_format_date($start_date, 'custom', 'd'),
        'month' => date_format_date($start_date, 'custom', 'M'),
        'year' => date_format_date($start_date, 'custom', 'Y'),
      ),
      'end' => array(
        'day' => date_format_date($end_date, 'custom', 'd'),
        'month' => date_format_date($end_date, 'custom', 'M'),
        'year' => date_format_date($end_date, 'custom', 'Y'),
      ),
    );

    $day = $dates['start']['day'];
    $month = $dates['start']['month'];
    $year = $dates['start']['year'];

    // Add year and use a different theme output.
    $element[0] = array(
      '#markup' => theme('iasc_meeting_date',
        array(
          'month' => $month,
          'day' => $day,
          'year' => $year,
        )
      ),
    );
  }

  return $element;
}

/**
 * Implements hook_theme().
 */
function iasc_meeting_theme($existing, $type, $theme, $path) {
  $theme = array(
    'iasc_meeting_date' => array(
      'template' => 'iasc-meeting-date',
      'path' => drupal_get_path('module', 'iasc_meeting') . '/templates',
      'variables' => array(
        'month' => NULL,
        'day' => NULL,
        'year' => NULL,
      ),
    ),
  );

  return $theme;
}
