<?php
/**
 * @file
 * Customizations for IASC Scrape, if needed.
 */

/**
 * Implements hook_init().
 */
function iasc_scrape_init() {
  require __DIR__ . '/IASC/vendor/autoload.php';
}

/**
 * Implements hook_menu().
 */
function iasc_scrape_menu() {
  $items = array();

  $items['admin/iasc-scrape'] = array(
    'title' => 'Scrape IASC',
    'page callback' => 'iasc_scrape_scrape',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function iasc_scrape_scrape() {
  $output = array();
  // Initially set credential values
  $username = $password = '';

  // Grab custom login credentials if set
  if (file_exists(__DIR__ . '/IASC/creds.php')) {
    require __DIR__ . '/IASC/creds.php';
  }

  $login = new IASC\Login($username, $password);

  $crawler = $login->crawler;
  $client = $login->client;

  for ($i = 1; $i < 5; $i++) {
    $contact = new IASC\Element\ContactElement($client, $crawler, $i);
    $output[] = print_r($contact->getValues(), TRUE);
  }

  $output[] = '<br /><br />-----------<br /><br />';

  $document = new IASC\Element\DocumentElement($client, $crawler);
  $output[] = print_r($document->getValues(), TRUE);

  $output[] = '<br /><br />-----------<br /><br />';

  $news = new IASC\Element\NewsElement($client, $crawler);
  $output[] = $news->getValues();

  return implode('', $output);
}
