<?php
/**
 * @file
 * Code for the iasc_search feature.
 */

include_once 'iasc_search.features.inc';

/**
 * Implements hook_form_alter().
 */
function iasc_search_form_alter(&$form, &$form_state, $form_id) {
  if (('search_form' == $form_id) || ('search_theme_form' == $form_id)) {
    $form['#submit'] = array('iasc_search_all_form_submit');
    if (!empty($form['basic']['keys'])) {
      $form['basic']['keys']['#size'] = '';
    }
  }
}

/**
 * Custom form submit handler to change redirect state of the form.
 */
function iasc_search_all_form_submit($form, &$form_state) {
  $keys = trim($form_state['values']['keys']);
  $module = !empty($form_state['values']['module']) ? $form_state['values']['module'] : 'site';
  $module = ($module === 'node') ? 'site' : $module;
  $form_state['redirect'] = array($module . '/search/' . $keys);
}

/**
 * Implements hook_block_info().
 */
function iasc_search_block_info() {
  $blocks['search_results_login_cta'] = array(
    'info' => t('Search Results - Login CTA'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function iasc_search_block_view($delta = '') {
$block = array();

  switch ($delta) {
    case 'search_results_login_cta':
      $block['subject'] = NULL;
      $dest = drupal_get_path_alias();
      $block['content'] = array(
        '#theme' => 'search_results_login_cta',
        '#dest' => drupal_get_path_alias(),
      );
      break;
  }
  return $block;
}

/**
 *  Implements hook_theme().
 */
function iasc_search_theme($existing, $type, $theme, $path) {
  $theme = array(
    'search_results_login_cta' => array(
      'template' => 'search-results-login-cta',
      'path' => drupal_get_path('module', 'iasc_search') . '/templates',
      'variables' => array(
        'dest' => '',
      ),
    ),
  );

  return $theme;
}