<?php
/**
 * @file
 * Code for the iasc_search feature.
 */

include_once 'iasc_search.features.inc';

/**
 * Implements hook_form_alter().
 */
function iasc_search_form_alter(&$form, &$form_state, $form_id) {
  if (('search_form' == $form_id) || ('search_theme_form' == $form_id)) {
    $form['#submit'] = array('iasc_search_all_form_submit');
    if (!empty($form['basic']['keys'])) {
      $form['basic']['keys']['#size'] = '';
    }
  }
}

/**
 *  Implements hook_form_FORM_ID_alter().
 *
 * Expose additional indexed fields are exposed.
 * By default only show text fields are displayed.
 */
function iasc_search_form_apachesolr_search_bias_form_alter(&$form, &$form_state, $form_id) {
  $fields = element_children($form['field_bias']);
  if ($fields) {
    foreach ($fields as $field_name) {
      // Show all the fields!
      $form['field_bias'][$field_name]['#access'] = TRUE;
    }
  }
}

/**
 * Custom form submit handler to change redirect state of the form.
 */
function iasc_search_all_form_submit($form, &$form_state) {
  $keys = trim($form_state['values']['keys']);
  $module = !empty($form_state['values']['module']) ? $form_state['values']['module'] : 'site';
  $module = ($module === 'node') ? 'site' : $module;
  $form_state['redirect'] = array($module . '/search/' . $keys);
}
