<?php
/**
 * @file
 * Code for the iasc_search feature.
 */

include_once 'iasc_search.features.inc';

/**
 * Implements hook_menu_alter().
 */
function iasc_search_menu_alter(&$items) {
  // Disable access to core search pages
  unset($items['search']);
  unset($items['search/site']);
  unset($items['search/node']);
  unset($items['search/site/%menu_tail']);
}

/**
 * Implements hook_form_alter().
 */
function iasc_search_form_alter(&$form, &$form_state, $form_id) {
  if (('search_form' == $form_id) || ('search_theme_form' == $form_id)) {
    $form['#action'] = '/site/search/';
    $form['#submit'] = array('iasc_search_all_form_submit');
    if (!empty($form['basic']['keys'])) {
      $form['basic']['keys']['#size'] = '';
    }
  }

  // Override the OA search toolbar. We want to use our panelized version for site search as the action and we don't want the
  // dropdown options.
  if ('apachesolr_panels_search_form' == $form_id && (FALSE === strpos($form['#action'], '/site/search/'))) {
    // Make our apachesolr search form look like the OA toolbar version.
    $form['#theme'] = 'iasc_search_form_toolbar';
    $form['apachesolr_panels_search_form']['#attributes']['class'][] = 'search-text';
    $form['#attached']['css'] = array(
        drupal_get_path('module', 'iasc_search') . '/css/search_toolbar.css',
    );
  }
}

/**
 * Custom form submit handler to change redirect state of the form.
 */
function iasc_search_all_form_submit($form, &$form_state) {
  $keys = trim($form_state['values']['keys']);
  $form_state['redirect'] = 'site/search/' . $keys;
}

/**
 * Implements hook_block_info().
 */
function iasc_search_block_info() {
  $blocks['search_results_login_cta'] = array(
    'info' => t('Search Results - Login CTA'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function iasc_search_block_view($delta = '') {
$block = array();

  switch ($delta) {
    case 'search_results_login_cta':
      $block['subject'] = NULL;
      $dest = drupal_get_path_alias();
      $block['content'] = array(
        '#theme' => 'search_results_login_cta',
        '#dest' => drupal_get_path_alias(),
      );
      break;
  }
  return $block;
}

/**
 *  Implements hook_theme().
 */
function iasc_search_theme($existing, $type, $theme, $path) {
  $theme = array(
    'search_results_login_cta' => array(
      'template' => 'search-results-login-cta',
      'path' => drupal_get_path('module', 'iasc_search') . '/templates',
      'variables' => array(
        'dest' => '',
      ),
    ),
    'iasc_search_form_toolbar' => array(
      'template' => 'iasc-search-form-toolbar',
      'render element' => 'element',
      'path' => drupal_get_path('module', 'iasc_search') . '/templates',
    ),
  );

  return $theme;
}
